/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 17:25:47 GMT 2024
 */

package org.apache.commons.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.validator.CreditCardValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreditCardValidator_ESTest extends CreditCardValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator(1843);
      // Undeclared exception!
      try { 
        creditCardValidator0.luhnCheck((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.CreditCardValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator(0);
      boolean boolean0 = creditCardValidator0.luhnCheck("4");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      boolean boolean0 = creditCardValidator0.luhnCheck("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      boolean boolean0 = creditCardValidator0.isValid("51,2,53,5455,");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      boolean boolean0 = creditCardValidator0.luhnCheck("91");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      boolean boolean0 = creditCardValidator0.isValid("org.apachv.coImons.validator.CreditCarbValidatorTest$DinezsClub");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      boolean boolean0 = creditCardValidator0.isValid("N5Hv'%kTw");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator(0);
      boolean boolean0 = creditCardValidator0.isValid((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator((-1036));
      assertEquals(2, CreditCardValidator.VISA);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator(889);
      assertEquals(4, CreditCardValidator.MASTERCARD);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
      CreditCardValidator.CreditCardType creditCardValidator_CreditCardType0 = mock(CreditCardValidator.CreditCardType.class, new ViolatedAssumptionAnswer());
      creditCardValidator0.addAllowedCardType(creditCardValidator_CreditCardType0);
      assertEquals(2, CreditCardValidator.VISA);
  }
}
