/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 18:13:04 GMT 2024
 */

package org.apache.commons.validator.routines.checkdigit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.validator.routines.checkdigit.EAN13CheckDigit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EAN13CheckDigit_ESTest extends EAN13CheckDigit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EAN13CheckDigit eAN13CheckDigit0 = (EAN13CheckDigit)EAN13CheckDigit.EAN13_CHECK_DIGIT;
      int int0 = eAN13CheckDigit0.weightedValue(736, 0, 0);
      assertEquals(2208, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EAN13CheckDigit eAN13CheckDigit0 = (EAN13CheckDigit)EAN13CheckDigit.EAN13_CHECK_DIGIT;
      int int0 = eAN13CheckDigit0.weightedValue((-1), 0, 736);
      assertEquals((-3), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EAN13CheckDigit eAN13CheckDigit0 = (EAN13CheckDigit)EAN13CheckDigit.EAN13_CHECK_DIGIT;
      // Undeclared exception!
      try { 
        eAN13CheckDigit0.weightedValue(736, 4186, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.EAN13CheckDigit", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EAN13CheckDigit eAN13CheckDigit0 = new EAN13CheckDigit();
      assertEquals(10, eAN13CheckDigit0.getModulus());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EAN13CheckDigit eAN13CheckDigit0 = (EAN13CheckDigit)EAN13CheckDigit.EAN13_CHECK_DIGIT;
      int int0 = eAN13CheckDigit0.weightedValue(0, 0, 0);
      assertEquals(0, int0);
  }
}
