/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 17:05:43 GMT 2024
 */

package org.apache.commons.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.apache.commons.collections.FastHashMap;
import org.apache.commons.validator.Field;
import org.apache.commons.validator.Form;
import org.apache.commons.validator.ValidatorAction;
import org.apache.commons.validator.ValidatorResults;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ValidatorAction_ESTest extends ValidatorAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMethodParams(" is not indexed");
      assertNull(validatorAction0.getClassname());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setDepends("ValidatorAction: null\n");
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJsFunction("-//Apache Software Foundation//DTD Commons Validator Rules Configuration 1.0//EN");
      validatorAction0.init();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setName(".  ");
      validatorAction0.getName();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setName("");
      validatorAction0.getName();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMsg("%n>u5f.EmRsC,1");
      validatorAction0.getMsg();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMsg("");
      validatorAction0.getMsg();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMethodParams("");
      String string0 = validatorAction0.getMethodParams();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMethod("Unknown field ");
      validatorAction0.getMethod();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJsFunctionName("]");
      validatorAction0.getJsFunctionName();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJavascript("  Loading function begun");
      validatorAction0.getJavascript();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJavascript("");
      validatorAction0.getJavascript();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setDepends("6{8>x");
      validatorAction0.getDepends();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setDepends("");
      validatorAction0.getDepends();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setClassName("Bzl4~c7TynD6t{");
      validatorAction0.getClassname();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setClassName("");
      validatorAction0.getClassname();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      // Undeclared exception!
      try { 
        validatorAction0.setMethodParams((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      // Undeclared exception!
      try { 
        validatorAction0.setDepends((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      Object[] objectArray0 = new Object[8];
      try { 
        validatorAction0.returnResult(objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setName("");
      // Undeclared exception!
      try { 
        validatorAction0.loadJavascriptFunction();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      // Undeclared exception!
      try { 
        validatorAction0.loadJavascriptFunction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJsFunction("");
      // Undeclared exception!
      try { 
        validatorAction0.init();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      Field field0 = new Field();
      // Undeclared exception!
      try { 
        validatorAction0.executeValidationMethod(field0, (Map<String, Object>) null, (ValidatorResults) null, 11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMethodParams("\n");
      assertNull(validatorAction0.getDepends());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJavascript("");
      // Undeclared exception!
      try { 
        validatorAction0.setJsFunction("\"L4");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot call setJsFunction() after calling setJavascript()
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setName("LS~V[%>W");
      validatorAction0.loadJavascriptFunction();
      // Undeclared exception!
      try { 
        validatorAction0.setJavascript("97h8UXKR`O5b-F#*7 ");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot call setJavascript() after calling setJsFunction()
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setDepends("\n");
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJavascript("zKC(Z(");
      validatorAction0.loadJavascriptFunction();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setDepends("zKC(Z(");
      boolean boolean0 = validatorAction0.isDependency("zKC(Z(");
      assertTrue(boolean0);
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      boolean boolean0 = validatorAction0.isDependency("LS~V[>W");
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setJsFunction("/");
      validatorAction0.loadJavascriptFunction();
      assertEquals("META-INF\norg\n", validatorAction0.getJavascript());
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getJavascript();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getDependencyList();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setMethod("");
      validatorAction0.getMethod();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getJsFunctionName();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      String string0 = validatorAction0.getMethodParams();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getDepends();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getName();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      Field field0 = new Field();
      Form form0 = new Form();
      FastHashMap fastHashMap0 = new FastHashMap(1605);
      ValidatorResults validatorResults0 = form0.validate(fastHashMap0, fastHashMap0, 12);
      validatorAction0.executeValidationMethod(field0, fastHashMap0, validatorResults0, 12);
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      String string0 = validatorAction0.toString();
      assertEquals("ValidatorAction: null\n", string0);
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      // Undeclared exception!
      try { 
        validatorAction0.init();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.ValidatorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.setClassname("r|t[WlT0^/");
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getMethod();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getMsg();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ValidatorAction validatorAction0 = new ValidatorAction();
      validatorAction0.getClassname();
      assertEquals("java.lang.Object,org.apache.commons.validator.ValidatorAction,org.apache.commons.validator.Field", validatorAction0.getMethodParams());
  }
}
