/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 18:08:20 GMT 2024
 */

package org.apache.commons.validator.routines.checkdigit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.validator.routines.checkdigit.LuhnCheckDigit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LuhnCheckDigit_ESTest extends LuhnCheckDigit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LuhnCheckDigit luhnCheckDigit0 = (LuhnCheckDigit)LuhnCheckDigit.LUHN_CHECK_DIGIT;
      int int0 = luhnCheckDigit0.weightedValue(0, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LuhnCheckDigit luhnCheckDigit0 = (LuhnCheckDigit)LuhnCheckDigit.LUHN_CHECK_DIGIT;
      // Undeclared exception!
      try { 
        luhnCheckDigit0.weightedValue(0, 4, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.LuhnCheckDigit", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LuhnCheckDigit luhnCheckDigit0 = (LuhnCheckDigit)LuhnCheckDigit.LUHN_CHECK_DIGIT;
      int int0 = luhnCheckDigit0.weightedValue(1803, 0, 0);
      assertEquals(3597, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LuhnCheckDigit luhnCheckDigit0 = (LuhnCheckDigit)LuhnCheckDigit.LUHN_CHECK_DIGIT;
      int int0 = luhnCheckDigit0.weightedValue((-5065), 6, 6);
      assertEquals((-10130), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LuhnCheckDigit luhnCheckDigit0 = new LuhnCheckDigit();
      try { 
        luhnCheckDigit0.calculate("9x");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid Character[2] = 'x'
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.ModulusCheckDigit", e);
      }
  }
}
