/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 17:37:34 GMT 2024
 */

package org.apache.commons.validator.routines.checkdigit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.validator.routines.checkdigit.VerhoeffCheckDigit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VerhoeffCheckDigit_ESTest extends VerhoeffCheckDigit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid("-P5-1>5EV919");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      try { 
        verhoeffCheckDigit0.calculate("$L|Ca6!L<MmWxS+m6");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid Character[1] = '109'
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.VerhoeffCheckDigit", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      String string0 = verhoeffCheckDigit0.calculate("99");
      assertEquals("4", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid("0");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid("4");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      boolean boolean0 = verhoeffCheckDigit0.isValid("'");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      try { 
        verhoeffCheckDigit0.calculate("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Code is missing
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.VerhoeffCheckDigit", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      VerhoeffCheckDigit verhoeffCheckDigit0 = new VerhoeffCheckDigit();
      try { 
        verhoeffCheckDigit0.calculate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Code is missing
         //
         verifyException("org.apache.commons.validator.routines.checkdigit.VerhoeffCheckDigit", e);
      }
  }
}
