/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 17:44:08 GMT 2024
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.text.DateFormat;
import java.util.Locale;
import org.apache.commons.validator.routines.ByteValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.text.MockDateFormat;
import org.evosuite.runtime.mock.java.text.MockSimpleDateFormat;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ByteValidator_ESTest extends ByteValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      DateFormat dateFormat0 = MockDateFormat.getDateTimeInstance(0, 2);
      Long long0 = new Long(127L);
      Object object0 = byteValidator0.processParsedValue(long0, dateFormat0);
      assertNotNull(object0);
      assertEquals((byte)127, object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Long long0 = new Long((-128L));
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat();
      Object object0 = byteValidator0.processParsedValue(long0, mockSimpleDateFormat0);
      assertEquals((byte) (-128), object0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Locale locale0 = Locale.ITALIAN;
      Byte byte0 = byteValidator0.validate("0", locale0);
      assertEquals((byte)0, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Locale locale0 = Locale.GERMAN;
      Byte byte0 = byteValidator0.validate("114", locale0);
      assertEquals((byte)114, (byte)byte0);
      assertNotNull(byte0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Locale locale0 = Locale.ITALIAN;
      Byte byte0 = byteValidator0.validate("-7", locale0);
      assertNotNull(byte0);
      assertEquals((byte) (-7), (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Locale locale0 = Locale.JAPAN;
      Byte byte0 = byteValidator0.validate("xi$$KAn0=N]", "xi$$KAn0=N]", locale0);
      assertEquals((byte)0, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Locale locale0 = Locale.GERMANY;
      Byte byte0 = byteValidator0.validate("114", "", locale0);
      assertNotNull(byte0);
      assertEquals((byte)114, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Locale locale0 = Locale.ENGLISH;
      Byte byte0 = byteValidator0.validate("-34", "", locale0);
      assertEquals((byte) (-34), (byte)byte0);
      assertNotNull(byte0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = byteValidator0.validate("0", "0");
      assertEquals((byte)0, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Byte byte0 = byteValidator0.validate("114", "");
      assertNotNull(byte0);
      assertEquals((byte)114, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Byte byte0 = byteValidator0.validate("-1", "");
      assertNotNull(byte0);
      assertEquals((byte) (-1), (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = byteValidator0.validate("0");
      assertEquals((byte)0, (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 60);
      Byte byte0 = byteValidator0.validate("2<deL,>IlsCW`i");
      assertEquals((byte)2, (byte)byte0);
      assertNotNull(byte0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Byte byte0 = byteValidator0.validate("-101");
      assertNotNull(byte0);
      assertEquals((byte) (-101), (byte)byte0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(true, 0);
      Locale locale0 = Locale.UK;
      // Undeclared exception!
      try { 
        byteValidator0.validate(">[gbPCNt\u0005PW;LK:", ">[gbPCNt\u0005PW;LK:", locale0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unquoted special character ';' in pattern \">[gbPCNt\u0005PW;LK:\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      // Undeclared exception!
      try { 
        byteValidator0.validate("\".", "u|ha$,*BD8kV+.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Malformed pattern \"u|ha$,*BD8kV+.\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      // Undeclared exception!
      try { 
        byteValidator0.minValue((Byte) null, (byte) (-49));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.ByteValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      // Undeclared exception!
      try { 
        byteValidator0.maxValue((Byte) null, (byte)114);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.ByteValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 1000);
      // Undeclared exception!
      try { 
        byteValidator0.isInRange((Byte) null, (byte)1, (byte)1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.ByteValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      boolean boolean0 = byteValidator0.minValue((byte)0, (byte)47);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      boolean boolean0 = byteValidator0.minValue((byte)100, (byte)0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      boolean boolean0 = byteValidator0.maxValue((byte)109, (byte) (-25));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      boolean boolean0 = byteValidator0.maxValue((byte) (-101), (byte)125);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      boolean boolean0 = byteValidator0.isInRange((byte)0, (byte) (-55), (byte)0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      boolean boolean0 = byteValidator0.isInRange((byte) (-101), (byte)0, (byte)109);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat();
      Long long0 = new Long(1035L);
      Object object0 = byteValidator0.processParsedValue(long0, mockSimpleDateFormat0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      DateFormat dateFormat0 = MockDateFormat.getDateTimeInstance(0, 2);
      Long long0 = new Long((-808L));
      Object object0 = byteValidator0.processParsedValue(long0, dateFormat0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      DateFormat dateFormat0 = MockDateFormat.getDateTimeInstance(0, 2);
      Object object0 = byteValidator0.processParsedValue("", dateFormat0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = new Byte((byte)86);
      boolean boolean0 = byteValidator0.minValue(byte0, (byte)86);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      Byte byte0 = new Byte((byte)109);
      boolean boolean0 = byteValidator0.maxValue(byte0, (byte)109);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      Byte byte0 = new Byte((byte)109);
      boolean boolean0 = byteValidator0.isInRange(byte0, (byte) (-25), (byte)125);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      boolean boolean0 = byteValidator0.isInRange((byte)85, (byte)85, (byte)46);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Locale locale0 = Locale.TRADITIONAL_CHINESE;
      Byte byte0 = byteValidator0.validate("85", "85", locale0);
      assertNull(byte0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator(false, 0);
      Byte byte0 = byteValidator0.validate("", (Locale) null);
      assertNull(byte0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = new Byte((byte)0);
      boolean boolean0 = byteValidator0.isInRange(byte0, (byte)1, (byte)1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Byte byte0 = byteValidator0.validate((String) null);
      assertNull(byte0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = byteValidator0.validate("85", "85");
      assertNull(byte0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ByteValidator byteValidator0 = ByteValidator.getInstance();
      Byte byte0 = new Byte((byte) (-105));
      boolean boolean0 = byteValidator0.minValue(byte0, (byte)80);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ByteValidator byteValidator0 = new ByteValidator();
      Byte byte0 = new Byte((byte)85);
      boolean boolean0 = byteValidator0.maxValue(byte0, (byte)46);
      assertFalse(boolean0);
  }
}
