/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 07 17:51:27 GMT 2024
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.Format;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import org.apache.commons.validator.routines.BigDecimalValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BigDecimalValidator_ESTest extends BigDecimalValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      boolean boolean0 = bigDecimalValidator0.minValue(bigDecimal0, 0.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false, 1936, false);
      BigInteger bigInteger0 = BigInteger.ZERO;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0, (-1));
      boolean boolean0 = bigDecimalValidator0.maxValue(bigDecimal0, (double) 1936);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      BigInteger bigInteger0 = BigInteger.ZERO;
      MathContext mathContext0 = MathContext.DECIMAL32;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0, mathContext0);
      boolean boolean0 = bigDecimalValidator0.isInRange(bigDecimal0, (-358.1682919), 1.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      Locale locale0 = Locale.US;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("0", locale0);
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      Locale locale0 = Locale.ITALIAN;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("9wo9|rr:\"", locale0);
      assertEquals((byte)9, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      Locale locale0 = Locale.JAPANESE;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("", "6ko{5&", locale0);
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      Locale locale0 = Locale.ITALIAN;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("1 LWau??|>O]", (String) null, locale0);
      assertNotNull(bigDecimal0);
      assertEquals((short)1, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      Locale locale0 = new Locale("1U90z=P", "");
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("-23", "", locale0);
      assertEquals((byte) (-23), bigDecimal0.byteValue());
      assertNotNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("", "");
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("10", "10");
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("0");
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("1");
      assertEquals((short)1, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("-23");
      assertEquals((short) (-23), bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      Long long0 = new Long(2911L);
      DecimalFormat decimalFormat0 = new DecimalFormat();
      BigDecimal bigDecimal0 = (BigDecimal)bigDecimalValidator0.processParsedValue(long0, decimalFormat0);
      assertEquals((byte)95, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      Locale locale0 = Locale.PRC;
      // Undeclared exception!
      try { 
        bigDecimalValidator0.validate("a_Yg;S{Cm6Y`sQ2bpYW", "a_Yg;S{Cm6Y`sQ2bpYW", locale0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unquoted special character ';' in pattern \"a_Yg;S{Cm6Y`sQ2bpYW\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(true);
      Locale locale0 = Locale.CHINA;
      DateFormat dateFormat0 = DateFormat.getTimeInstance(0, locale0);
      // Undeclared exception!
      try { 
        bigDecimalValidator0.processParsedValue((Object) null, dateFormat0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(true);
      Long long0 = new Long(2);
      DateTimeFormatter dateTimeFormatter0 = DateTimeFormatter.ISO_ORDINAL_DATE;
      Format format0 = dateTimeFormatter0.toFormat();
      // Undeclared exception!
      try { 
        bigDecimalValidator0.processParsedValue(long0, format0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.time.format.DateTimeFormatter$ClassicFormat cannot be cast to java.text.NumberFormat
         //
         verifyException("org.apache.commons.validator.routines.BigDecimalValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(true);
      // Undeclared exception!
      try { 
        bigDecimalValidator0.minValue((BigDecimal) null, (double) 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.BigDecimalValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(false);
      // Undeclared exception!
      try { 
        bigDecimalValidator0.maxValue((BigDecimal) null, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.BigDecimalValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator(true, (-907), false);
      // Undeclared exception!
      try { 
        bigDecimalValidator0.isInRange((BigDecimal) null, (double) (-907), (double) (-907));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.BigDecimalValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("10", "");
      assertNotNull(bigDecimal0);
      assertEquals((short)10, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      // Undeclared exception!
      try { 
        bigDecimalValidator0.processParsedValue("1", (Format) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      boolean boolean0 = bigDecimalValidator0.minValue(bigDecimal0, (double) 0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = new BigDecimal((double) 1);
      boolean boolean0 = bigDecimalValidator0.minValue(bigDecimal0, (double) 2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      boolean boolean0 = bigDecimalValidator0.maxValue(bigDecimal0, (double) 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      boolean boolean0 = bigDecimalValidator0.maxValue(bigDecimal0, (double) 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      boolean boolean0 = bigDecimalValidator0.isInRange(bigDecimal0, (double) 2, (double) 2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      BigDecimal bigDecimal0 = new BigDecimal((double) 1);
      boolean boolean0 = bigDecimalValidator0.isInRange(bigDecimal0, (double) 1, (double) 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      boolean boolean0 = bigDecimalValidator0.isInRange(bigDecimal0, (double) 1, (double) 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("");
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      // Undeclared exception!
      try { 
        bigDecimalValidator0.validate("OVT;tO", "OVT;tO");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unquoted special character ';' in pattern \"OVT;tO\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = BigDecimalValidator.getInstance();
      Locale locale0 = Locale.US;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("*_0U!", "*_0U!", locale0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      BigDecimalValidator bigDecimalValidator0 = new BigDecimalValidator();
      Locale locale0 = Locale.ITALY;
      BigDecimal bigDecimal0 = bigDecimalValidator0.validate("org.apache.commons.validator.routines.AbstractNumberValidator", locale0);
      assertNull(bigDecimal0);
  }
}
